/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AllergiesRouteImport } from './routes/allergies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmergencyTokenRouteImport } from './routes/emergency.$token'

const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AllergiesRoute = AllergiesRouteImport.update({
  id: '/allergies',
  path: '/allergies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyTokenRoute = EmergencyTokenRouteImport.update({
  id: '/emergency/$token',
  path: '/emergency/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allergies': typeof AllergiesRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/qr': typeof QrRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/emergency/$token': typeof EmergencyTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allergies': typeof AllergiesRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/qr': typeof QrRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/emergency/$token': typeof EmergencyTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allergies': typeof AllergiesRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/qr': typeof QrRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/emergency/$token': typeof EmergencyTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/allergies'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/medications'
    | '/prescriptions'
    | '/qr'
    | '/reports'
    | '/scan'
    | '/scans'
    | '/settings'
    | '/signup'
    | '/summary'
    | '/emergency/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/allergies'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/medications'
    | '/prescriptions'
    | '/qr'
    | '/reports'
    | '/scan'
    | '/scans'
    | '/settings'
    | '/signup'
    | '/summary'
    | '/emergency/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/allergies'
    | '/dashboard'
    | '/help'
    | '/login'
    | '/medications'
    | '/prescriptions'
    | '/qr'
    | '/reports'
    | '/scan'
    | '/scans'
    | '/settings'
    | '/signup'
    | '/summary'
    | '/emergency/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllergiesRoute: typeof AllergiesRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  QrRoute: typeof QrRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  ScansRoute: typeof ScansRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SummaryRoute: typeof SummaryRoute
  EmergencyTokenRoute: typeof EmergencyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allergies': {
      id: '/allergies'
      path: '/allergies'
      fullPath: '/allergies'
      preLoaderRoute: typeof AllergiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/$token': {
      id: '/emergency/$token'
      path: '/emergency/$token'
      fullPath: '/emergency/$token'
      preLoaderRoute: typeof EmergencyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllergiesRoute: AllergiesRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  QrRoute: QrRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  ScansRoute: ScansRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SummaryRoute: SummaryRoute,
  EmergencyTokenRoute: EmergencyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
